yolo_out_json = 'results/result_OLD.json'
yolo_test_data = 'C:\Traffic_Signs/ts'
yolo_cropped_img = 'C:\Traffic_Signs\cropped/'
to_save_cropped_img_folder = 'results/cropped/'
german_dataset_root = 'C:\Datasety\German-classification'
#network_weights = 'C:\Datasety\German-classification/training/TSR.h5'
network_weights = 'weights/TSR.h5'
log_from_classification = 'C:\Traffic_Signs\log.txt'
#nieuzywane
results = 'results/'
